# Generated by Django 6.0.6 on 2026-06-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='catalogo.autor', verbose_name='Autor')),
            ],
        ),
    ]
