# Generated by Django 6.0.6 on 2026-06-08 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data de Empréstimo')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de Devolução Prevista')),
                ('data_devolucao_real', models.DateField(blank=True, null=True, verbose_name='Data de Devolução Real')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor da Multa')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='catalogo.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Leitor')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True, verbose_name='Data de Reserva')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalogo.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Leitor')),
            ],
        ),
    ]
